[[pages]]
width = 8
height = 5
  [[pages.frames]]
  top = 1
  left = 1
  width = 4
  height = 1
    [pages.frames.contents]
    widget = "greeting"
    [pages.frames.contents.config]
    name = "Cam"
  [[pages.frames]]
  top = 5
  left = 7
  width = 2
  height = 1
    [pages.frames.contents]
    widget = "clock"
    [pages.frames.contents.config]
    style = "digital"
    hour-format = 12
    show-seconds = false
