mode = "mirror"
name = "Bedroom Mirror"
voice = true

[[pages]]
width = 16
height = 9
  [[pages.frames]]
  top = 2
  left = 2
  width = 4
  height = 1
    [pages.frames.contents]
    widget = "greeting"
    [pages.frames.contents.config]
    name = "Cam"
  [[pages.frames]]
  top = 8
  left = 15
  width = 2
  height = 2
    [pages.frames.contents]
    widget = "clock"
    [pages.frames.contents.config]
    style = "analog"
    hour-format = 12
    show-seconds = true
  [[pages.frames]]
  top = 8
  left = 0
  width = 4
  height = 2
    [pages.frames.contents]
    widget = "weather"

[[pages]]
width = 16
height = 9
  [[pages.frames]]
  top = 2
  left = 2
  width = 4
  height = 1
    [pages.frames.contents]
    widget = "greeting"
    [pages.frames.contents.config]
    name = "Pearl"
  [[pages.frames]]
  top = 8
  left = 15
  width = 2
  height = 2
    [pages.frames.contents]
    widget = "clock"
